spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/fiie_db
spring.datasource.username=postgres
spring.datasource.password=postgresfiie

server.address=0.0.0.0

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Multipart file upload configuration
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=30MB
spring.servlet.multipart.max-request-size=35MB